/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OurScienceRouteImport } from './routes/our-science'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsDswRouteImport } from './routes/products.dsw'
import { Route as ProductsDesireForMenRouteImport } from './routes/products.desire-for-men'
import { Route as ProductsDesireForCouple2bottles159800RouteImport } from './routes/products.desire-for-couple-2bottles-1-598-00'
import { Route as ApiDownloadRouteImport } from './routes/api/download'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OurScienceRoute = OurScienceRouteImport.update({
  id: '/our-science',
  path: '/our-science',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsDswRoute = ProductsDswRouteImport.update({
  id: '/dsw',
  path: '/dsw',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsDesireForMenRoute = ProductsDesireForMenRouteImport.update({
  id: '/desire-for-men',
  path: '/desire-for-men',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsDesireForCouple2bottles159800Route =
  ProductsDesireForCouple2bottles159800RouteImport.update({
    id: '/desire-for-couple-2bottles-1-598-00',
    path: '/desire-for-couple-2bottles-1-598-00',
    getParentRoute: () => ProductsRoute,
  } as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/our-science': typeof OurScienceRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRouteWithChildren
  '/api/download': typeof ApiDownloadRoute
  '/products/desire-for-couple-2bottles-1-598-00': typeof ProductsDesireForCouple2bottles159800Route
  '/products/desire-for-men': typeof ProductsDesireForMenRoute
  '/products/dsw': typeof ProductsDswRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/our-science': typeof OurScienceRoute
  '/our-story': typeof OurStoryRoute
  '/api/download': typeof ApiDownloadRoute
  '/products/desire-for-couple-2bottles-1-598-00': typeof ProductsDesireForCouple2bottles159800Route
  '/products/desire-for-men': typeof ProductsDesireForMenRoute
  '/products/dsw': typeof ProductsDswRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/our-science': typeof OurScienceRoute
  '/our-story': typeof OurStoryRoute
  '/products': typeof ProductsRouteWithChildren
  '/api/download': typeof ApiDownloadRoute
  '/products/desire-for-couple-2bottles-1-598-00': typeof ProductsDesireForCouple2bottles159800Route
  '/products/desire-for-men': typeof ProductsDesireForMenRoute
  '/products/dsw': typeof ProductsDswRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/complete'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/our-science'
    | '/our-story'
    | '/products'
    | '/api/download'
    | '/products/desire-for-couple-2bottles-1-598-00'
    | '/products/desire-for-men'
    | '/products/dsw'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/complete'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/our-science'
    | '/our-story'
    | '/api/download'
    | '/products/desire-for-couple-2bottles-1-598-00'
    | '/products/desire-for-men'
    | '/products/dsw'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/complete'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/our-science'
    | '/our-story'
    | '/products'
    | '/api/download'
    | '/products/desire-for-couple-2bottles-1-598-00'
    | '/products/desire-for-men'
    | '/products/dsw'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompleteRoute: typeof CompleteRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OurScienceRoute: typeof OurScienceRoute
  OurStoryRoute: typeof OurStoryRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ApiDownloadRoute: typeof ApiDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-science': {
      id: '/our-science'
      path: '/our-science'
      fullPath: '/our-science'
      preLoaderRoute: typeof OurScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/dsw': {
      id: '/products/dsw'
      path: '/dsw'
      fullPath: '/products/dsw'
      preLoaderRoute: typeof ProductsDswRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/desire-for-men': {
      id: '/products/desire-for-men'
      path: '/desire-for-men'
      fullPath: '/products/desire-for-men'
      preLoaderRoute: typeof ProductsDesireForMenRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/desire-for-couple-2bottles-1-598-00': {
      id: '/products/desire-for-couple-2bottles-1-598-00'
      path: '/desire-for-couple-2bottles-1-598-00'
      fullPath: '/products/desire-for-couple-2bottles-1-598-00'
      preLoaderRoute: typeof ProductsDesireForCouple2bottles159800RouteImport
      parentRoute: typeof ProductsRoute
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsDesireForCouple2bottles159800Route: typeof ProductsDesireForCouple2bottles159800Route
  ProductsDesireForMenRoute: typeof ProductsDesireForMenRoute
  ProductsDswRoute: typeof ProductsDswRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsDesireForCouple2bottles159800Route:
    ProductsDesireForCouple2bottles159800Route,
  ProductsDesireForMenRoute: ProductsDesireForMenRoute,
  ProductsDswRoute: ProductsDswRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompleteRoute: CompleteRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OurScienceRoute: OurScienceRoute,
  OurStoryRoute: OurStoryRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ApiDownloadRoute: ApiDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
